---
- name: Install required system packages
  apt:
    pkg:
      - docker.io
      - docker-compose
    state: latest
    update_cache: true
    
- name: Stop service docker, if started
  ansible.builtin.service:
    name: docker
    state: stopped

- name: Restart service docker, if started
  ansible.builtin.service:
    name: docker
    state: restarted
- name: Add user to docker group
  user:
    name: "{{ ansible_ssh_user }}"
    group: docker
    append: yes

- name: Enable service docker, if started
  ansible.builtin.service:
    name: docker
    enabled: yes

- name: Ensure Docker is running
  ansible.builtin.service:
    name: docker
    state: started

