---
- name: Install required system packages
  apt:
    pkg:
      - docker.io
      - docker-compose
    state: latest
    update_cache: true
    
- name: Stop service docker, if started
  ansible.builtin.service:
    name: docker
    state: stopped

- name: Restart service docker, if started
  ansible.builtin.service:
    name: docker
    state: restarted

- name: Enable service docker, if started
  ansible.builtin.service:
    name: docker
    enabled: yes
