- name: Create a directory for {{ service_name }}
  ansible.builtin.file:
    path: ~/{{ service_name }}
    state: directory
    mode: "0755"


- name: Copy {{ service_name }} compose file
  template:
    src: docker-compose.{{ service_name }}.yml.j2
    dest: ~/{{ service_name }}/docker-compose.yml

- name: Stop and start {{ service_name }}
  ansible.builtin.shell: docker-compose down && docker-compose up -d
  args:
    chdir: ~/{{ service_name }}/
