---
- name: Install required system packages (curl)
  apt:
    pkg:
      - curl
    state: latest
    update_cache: true

- name: install jellyfin media server
  vars:
    users:
      - name: root
        passwd: whyone
  shell: |-
    curl https://repo.jellyfin.org/install-debuntu.sh | sudo bash
