---
- hosts: databases
  become: true
  roles:
    - dockerd
  vars_files:
    - databases.env.yml
  vars:
  tasks:
    - include_tasks: roles/compose.yml
      with_items: "{{ roles }}"
      vars:
        service_name: "{{ item }}"
