---
- name: Install and Configure Samba
  hosts: files_media
  become: yes
  vars:
    - user_password: whyone
    - roles:
        - jellyfin
  roles:
    - samba
    - dockerd
  tasks:
    - include_tasks: roles/compose.yml
      with_items: "{{ roles }}"
      vars:
        service_name: "{{ item }}"
